/// ╔═══════════════════════════════════╗
/// ║	Globals							║
/// ╚═══════════════════════════════════╝
/// ╔═══════════════════════════════════╗
/// ║	AI Adaptive Money Flow Index	║
/// ╔═══════════════════════════════════╗
/// ║	Adx Di Di						║
/// ╔═══════════════════════════════════╗
/// ║	Tsi & Divergences				║
/// ╚═══════════════════════════════════╝
/// ╔═══════════════════════════════════╗
/// ║	Panel Tsi MultiTimeframes		║
/// ║	@	Allen.						║
/// ╚═══════════════════════════════════╝
/// ╔═══════════════════════════════════╗
/// ║	Panel Multi Indicators			║
/// ║	@	Allen.						║
/// ╚═══════════════════════════════════╝

//@version=5
indicator(title							= 'AI Mfi & AdxDiDi & Tsi Div & Panels Tsi Mtf - MIn [🎱 Allen 㔬]',
		  shorttitle					= 'AiMfi & AdxDi & MTsi & PTsi MIn',
		  format						= format.price,
		  precision						= 4
		  )

//// ─────────────────────────────────────────────────────────────────────

/// ─── Colors
	// AmeTrBlueFrost							= #E1EEF9
	// CitiAccentUltraLightBlue					= #E6F7FF
	// MongoSky10								= #E3FCF7
	// BrLiYel10								= #FBFD73
	// BrLiYel30								= #FDF43C
	// PlatziGreen30							= #ADEB42
	// SurfeGray600								= #49575B
	// SurfeSeaweed100							= #073742
	// PlatziBlue70								= #121F3D
	// PlatziBlue80								= #0C1633
	// AllenSky10								= #CCF8FF
	// AllenMint60								= #33FFAC
	// AllenFucsia50							= #EA1889

	// GraySwebSeasalt		    				= #FAFAFC
	// SurfeGray100								= #F4F5F6
	// SurfeSunrise100							= #FEFFD6
	// SurfeSunrise300							= #FCFF8F
	// SurfeHorizon200							= #FFBCF0
	// SurfeSecondary							= #FFA2EA
	// SurfeSky300								= #BDEDFC
	// SurfeSky400								= #88D7F0
	// SurfeGray450								= #5C818A
	// SurfeSeaweed100							= #073742
	// MongoBlack50								= #231F20

	// MongoLime50								= #B1FF05
	// PlatziGreen50							= #95CA3E
	// AllenWine60								= #E8114B

	// Axi7a46f22								= #D11C36
	// AxiPrimary								= #FC404D
	// ARoPrimary								= #0035FF
	// ARoSecondary		    					= #04EBFF

	// TvBuy									= #2962FF
	// TvSell									= #F23645
	// EEGFucsia50								= #FE0CB6
	// EEGSkyBlue40								= #00E7FD

	// PandaVeryLightgray						= #E6E6E6
	// PandaLighterGray							= #CDCDCD
	// PandaLightGray							= #757575
	// PandaGray								= #373B41
	// PandaDarkGray							= #2E2F30
	// PandaVeryDarkGray						= #292A2B
	// PandaWhite								= #F3F3F3
	// PandaLightmidight						= #676B79

//// ─────────────────────────────────────────────────────────────────────

strGlobalExtendTooltip					= "Indicador TSI basado en tendencia"
strGlobalOptionalTooltip				= "Configuración de temporalidad adicional"

/// ───────────────────────
/// ─── Variables
/// ───────────────────────

globalTSIGroupTimeframe					= "Tsi & Divergences"
// globalTSIGroupTimeframe					= "Temporalidad Global"
showTsiMuDiTSIDivergs					= input.bool	(defval = true,			title = 'TSI & Divergences',			group = globalTSIGroupTimeframe)
showTsiMuDiTSITendency					= input.bool	(defval = true,			title = "Tsi de Tendencia",				group = globalTSIGroupTimeframe,		tooltip = strGlobalOptionalTooltip)
showTsiMuDiTSIMultitimeframe			= input.bool	(defval = false,		title = "Tsi Multitimeframe",			group = globalTSIGroupTimeframe,		tooltip = strGlobalOptionalTooltip)
strGlobalMultiTimeFrame					= input.string 	(defval = "Grafico",	title = "Multi Timeframe",				group = globalTSIGroupTimeframe,
			  options					=				["Grafico", "15 min", "30 min", "1 Hora", "2 Horas", "3 Horas", "4 Horas", "1 Dia", "1 Semana", "1 Mes"])
strGlobalMultiHistogram					= input.string 	(defval = "Mfi",		title = "Histograma",					group = globalTSIGroupTimeframe,
			  options					=				["Mfi", "Adx"])
strGlobalColorSelector					= input.string 	(defval = "Allen",		title = "Color Selector",				group = globalTSIGroupTimeframe,
			  options					=				["Allen", "Ultr", "Inverse", "Classic", "Light", "Mono"])
insGlobalTFCoefficient					= 				2

/// ───────────────────────
/// ─── Types
/// ───────────────────────

type globalTypeOHL
	float O								= open
	float H								= high
	float L								= low
	float C								= close
	float V								= volume
	int   I								= bar_index

/// ───────────────────────
/// ─── Switch
/// ───────────────────────

[color_gbl_buy, color_gbl_sell, color_gbl_long, color_gbl_short, color_gbl_neutral, color_gbl_extra, color_gbl_white, color_gbl_black, color_gbl_text]		= switch		strGlobalColorSelector
	"Allen"								=> [#33FFAC,		#CCF8FF,		#ADEB42,		#EA1889,		#E1EEF9,		#FDF43C,		#E6F7FF,		#121F3D,		#121F3D]
	"Ultr"								=> [#00E7FD,		#FE0CB6,		#00E7FD,		#FE0CB6,		#121F3D,		#FDF43C,		#E6F7FF,		#0C1633,		#F3F3F3]
	"Light"								=> [#2962FF,		#F23645,		#2962FF,		#F23645,		#FCFF8F,		#5C818A,		#E1EEF9,		#073742,		#073742]
	"Inverse"							=> [#ADEB42,		#EA1889,		#33FFAC,		#CCF8FF,		#E6F7FF,		#FDF43C,		#E6F7FF,		#073742,		#073742]
	"Classic"							=> [#B1FF05,		#D11C36,		#B1FF05,		#D11C36,		#5C818A,		#FCFF8F,		#F4F5F6,		#0C1633,		#F3F3F3]
	"Mono"								=> [#E6E6E6,		#292A2B,		#FEFFD6,		#231F20,		#676B79,		#FCFF8F,		#F3F3F3,		#292A2B,		#F3F3F3]

/// ───────────────────────
/// ─── Functions
/// ───────────────────────

/// ─── function timeframe
FunGlobalTimeFrame(_timeframe) =>
	switch _timeframe
		"Grafico"						=> timeframe.period
		"1 seg"							=> "S"	
		"5 seg"							=> "5S"
		"10 seg"						=> "10S"
		"15 seg"						=> "15S"
		"30 seg"						=> "30S"
		"1 min"							=> "1"	
		"3 min"							=> "3"	
		"5 min"							=> "5"
		"15 min"						=> "15"
		"30 min"						=> "30"
		"1 Hora"						=> "60"
		"2 Horas"						=> "120"
		"3 Horas"						=> "180"
		"4 Horas"						=> "240"
		"8 horas"						=> "480"
		"Dia"							=> "D"
		"1 Dia"							=> "1D"
		"Semana"						=> "W"
		"1 Semana"						=> "1W"
		"Mes"							=> "M"
		"1 Mes"							=> "1M"

/// ─── function location vertical
FunGlobalVertical(_vertical) =>
	switch _vertical
		"arriba"						=> "top"
		"medio"							=> "middle"
		"abajo"							=> "bottom"

/// ─── function location horizontal
FunGlobalHorizontal(_horizontal) =>
	switch _horizontal

		"izquierda"						=> "left"
		"centro"						=> "center"
		"derecha"						=> "right"

/// ─── function position
FunGlobalPosition(_position) =>
	switch _position
		"Externo"						=> "outside"
		"Interno"						=> "inside"

/// ─── function text size
FunGlobalTextSize(_textsize) =>
	switch _textsize
		"Mini"							=> size.tiny
		"Pequeño"						=> size.small
		"Normal"						=> size.normal
		"Grande"						=> size.large
		"Enorme"						=> size.huge
		"Auto"							=> size.auto

/// ─── function line style
FunGlobalLineStyle(_linestyle) =>
	switch _linestyle
		'⎯⎯⎯⎯'							=> line.style_solid
		'----'							=> line.style_dashed
		'····'							=> line.style_dotted

/// ─── function Days of Week
FunGlobalDayofWeek(_days) =>
	switch _days
		1								=> 'Domingo'
		2								=> 'Lunes'
		3								=> 'Martes'
		4								=> 'Miercoles'
		5								=> 'Jueves'
		6								=> 'Viernes'
		7								=> 'Sabado'

/// ─── function Timezone
FunGlobalTimeZone(_timezone) =>
	switch _timezone
		"NYSE"							=> "UTC-5"
		"New York"						=> "America/New_York"
		"Chicago"						=> "America/Chicago"
		"Londres"						=> "Europe/London"
		"Tokyo"							=> "Asia/Tokyo"
		"Shanghai"						=> "Asia/Shanghai"
		"Sydney"						=> "Australia/Sydney"
		"Argentina"						=> "America/Argentina/Buenos_Aires"


/// ─── function calculate MA
FunGlobalCalculateMA(_source, _length, _type) =>
	switch _type
		"SMA"							=> ta.sma	(_source, _length)
		"HMA"							=> ta.hma	(_source, _length)
		"EMA"							=> ta.ema	(_source, _length)
		"SMMA"							=> ta.rma	(_source, _length)
		"WMA"							=> ta.wma	(_source, _length)
		"VWMA"							=> ta.vwma	(_source, _length)
		"MFI"							=> ta.mfi	(_source, _length)

/// ─── Function calculate timeframe range
FunGlobalCalculateTimeframeRange(_coefficient, _timeframe) =>
	_x									= 3
	_mayor								= 480
	_minor								= 15
	_tonumber							= str.tonumber(_timeframe)
	_operat_coeff						= _tonumber * _coefficient
	_operat_minor						= _tonumber * _x
	_toresult							= str.tonumber(_timeframe)
	_conditional						= _tonumber >= _mayor ? _toresult : _tonumber <= _minor ? _operat_minor : _operat_coeff
	str.tostring(_conditional)

/// ───────────────────────
/// ─── Instances
/// ───────────────────────

globalOHL								= globalTypeOHL.new()

//// ─────────────────────────────────────────────────────────────────────

/// ╔═══════════════════════════════════╗
/// ║	AI Adaptative MFI				║
/// ╚═══════════════════════════════════╝

//// ─────────────────────────────────────────────────────────────────────

adapMonToolAdj							= "Ajusta el MFI en su lugar para que los niveles de Sobrecompra, Sobreventa y Neutral permanezcan fijos"

adapMonGrpSet							= "Adaptative MFI"
adapMonGrpLim							= "Clustering Setting"
adapMonGrpApar							= "Apariencia"

//// ───────────────────────
/// ─── Adaptive MFI
/// ─── Vars ─────────
//// ───────────────────────

showadapMonGroup						= input.bool	(defval = true,				title = 'Mostrar Ai Adaptative MFI',						group = adapMonGrpSet)

adapMonVarADJ							= input.bool	(defval = true,				title = "Usar MFI ajustado",								group = adapMonGrpApar,		tooltip = adapMonToolAdj)
adapMonColorLong						= 				color_gbl_buy
adapMonColorShort						= 				color_gbl_sell
adapMonColorAux							= 				color_gbl_white
adapMonColorDark						= 				color_gbl_black

adapMonVarSRC							= input.source	(defval = hlc3,				title = "Fuente MFI",										group = adapMonGrpSet)
adapMonVarLENGTH						= input.int		(defval = 14,				title = "Longitud MFI",							minval = 1,	group = adapMonGrpSet)
adapMonVarDataLength					= input.int		(defval = 300,				title = "Nº de datos de entrenamiento",			minval = 1,	group = adapMonGrpLim)
adapMonVarIterations					= input.int		(defval = 5,				title = "Nº de iteraciones por barra",			minval = 1,	group = adapMonGrpLim)

float adapMonVarOverbought				= 75.0			// 80.0
float adapMonVarNeutral					= 50.0
float adapMonVarOversold				= 25.0			// 20.0

//// ───────────────────────
/// ─── Adaptive MFI
/// ─── Functions ────
//// ───────────────────────

adapMonVarOSC							= ta.mfi(adapMonVarSRC, adapMonVarLENGTH)

var adapMonArrOB						= array.new_float(1, adapMonVarOverbought)
var adapMonArrNE						= array.new_float(1, adapMonVarNeutral)
var adapMonArrOS						= array.new_float(1, adapMonVarOversold)

adapMonArrNE_NEW						= array.avg(adapMonArrNE)
adapMonArrOB_NEW						= array.avg(adapMonArrOB)
adapMonArrOS_NEW						= array.avg(adapMonArrOS)

positionBetweenBands					= 100 * ((adapMonVarOSC - adapMonArrOS_NEW)/(adapMonArrOB_NEW - adapMonArrOS_NEW))

adapMonIfVAL							= adapMonVarADJ ? positionBetweenBands : adapMonVarOSC

adapMonFuncST							= ta.stdev(adapMonIfVAL, adapMonVarLENGTH)

adapMonIfCOLOR100						= adapMonVarOSC > adapMonArrNE_NEW		? color.new(adapMonColorLong, 90)		: color.new(adapMonColorShort, 90)
adapMonIfCOLOR0							= adapMonVarOSC > adapMonArrNE_NEW		? color.new(adapMonColorLong, 0)		: color.new(adapMonColorShort, 0)

//// ───────────────────────
/// ─── Adaptive MFI
/// ─── Display ──────
//// ───────────────────────

adapMonPlotMAIN							= plot	(strGlobalMultiHistogram == "Mfi" and showadapMonGroup ? adapMonIfVAL : na,						color = adapMonIfCOLOR100)
adapMonPlotMID							= plot	(strGlobalMultiHistogram == "Mfi" and showadapMonGroup and adapMonVarADJ ? adapMonVarNeutral : adapMonArrNE_NEW, color = adapMonIfCOLOR100)

/// ─── plot marcas de sobrecompra y sobreventa
plot									(showadapMonGroup ? adapMonVarADJ ? 110 : adapMonArrOB_NEW : na,										color = color.from_gradient(adapMonVarOSC, adapMonArrNE_NEW, adapMonVarADJ ? 100 : adapMonArrOB_NEW, color.new(adapMonColorDark, 70), color.new(adapMonColorShort, 0)),	linewidth = 6)
plot									(showadapMonGroup ? adapMonVarADJ ? -10 : adapMonArrOS_NEW : na,										color = color.from_gradient(adapMonVarOSC, adapMonVarADJ ? 0 : adapMonArrOS_NEW, adapMonArrNE_NEW, color.new(adapMonColorLong, 0), color.new(adapMonColorDark, 70)),	linewidth = 6)

/// ─── fill areas de tendencia
fill									(adapMonPlotMID, adapMonPlotMAIN,																		color = adapMonIfCOLOR100, title = "Area de Tendencia")
fill									(adapMonPlotMID, adapMonPlotMAIN, adapMonIfVAL, adapMonVarADJ ? 50 : adapMonArrNE_NEW,					color.new(chart.bg_color, 1000), adapMonVarOSC > adapMonArrNE_NEW ? adapMonColorLong : adapMonColorShort)

//// ─────────────────────────────────────────────────────────────────────
//// ─────────────────────────────────────────────────────────────────────
//// ─────────────────────────────────────────────────────────────────────

/// ╔═══════════════════════════════════════╗
/// ║	Adx Histogram						║
/// ║	@	Allen.							║
/// ╚═══════════════════════════════════════╝

//// ─────────────────────────────────────────────────────────────────────

colorxAdxDiHi_Buy						= color_gbl_buy
colorxAdxDiHi_Short						= color_gbl_sell
colorxAdxDiHi_Mid						= color_gbl_extra
colorxAdxDiHi_Extra						= color_gbl_extra

//// ───────────────────────
/// ─── Vars ───
//// ───────────────────────

AdxDiHiGroupVars						= "Adx Setting"
adxDiHi_Length							= input.int(defval = 14,		title = "Longitud Adx",			group = AdxDiHiGroupVars)
adxDiHi_Th								= input.int(defval = 25,		title = "Umbral",				group = AdxDiHiGroupVars)

//// ───────────────────────
/// ─── Functions ───
//// ───────────────────────
xAdxDiHi_TrueRange						= math.max(math.max(high - low, math.abs(high - nz(close[1]))), math.abs(low - nz(close[1])))
xAdxDiHi_DirectMovePlus					= high - nz(high[1]) > nz(low[1]) - low ? math.max(high - nz(high[1]), 0) : 0
xAdxDiHi_DirectMoveMinus				= nz(low[1]) - low > high - nz(high[1]) ? math.max(nz(low[1]) - low, 0) : 0

var float xAdxDiHi_SmoothTrueRange		= na
var float xAdxDiHi_SmoothDirectMovePlus	= na
var float xAdxDiHi_SmoothDirectMoveMinus= na

xAdxDiHi_SmoothTrueRange				:= na(xAdxDiHi_SmoothTrueRange) ? xAdxDiHi_TrueRange : xAdxDiHi_SmoothTrueRange - (xAdxDiHi_SmoothTrueRange / adxDiHi_Length) + xAdxDiHi_TrueRange
xAdxDiHi_SmoothDirectMovePlus			:= na(xAdxDiHi_SmoothDirectMovePlus) ? xAdxDiHi_DirectMovePlus : xAdxDiHi_SmoothDirectMovePlus - (xAdxDiHi_SmoothDirectMovePlus / adxDiHi_Length) + xAdxDiHi_DirectMovePlus
xAdxDiHi_SmoothDirectMoveMinus			:= na(xAdxDiHi_SmoothDirectMoveMinus) ? xAdxDiHi_DirectMoveMinus : xAdxDiHi_SmoothDirectMoveMinus - (xAdxDiHi_SmoothDirectMoveMinus / adxDiHi_Length) + xAdxDiHi_DirectMoveMinus

//// ───────────────────────
/// ─── Maths ───
//// ───────────────────────

xAdxDiHi_DIPlus							= xAdxDiHi_SmoothDirectMovePlus / xAdxDiHi_SmoothTrueRange * 100
xAdxDiHi_DIMinus						= xAdxDiHi_SmoothDirectMoveMinus / xAdxDiHi_SmoothTrueRange * 100
xAdxDiHi_DX								= math.abs(xAdxDiHi_DIPlus - xAdxDiHi_DIMinus) / (xAdxDiHi_DIPlus + xAdxDiHi_DIMinus) * 100
xAdxDiHi_ADX							= ta.sma(xAdxDiHi_DX, adxDiHi_Length)

xAdxDiHi_Didi							= 25 + (xAdxDiHi_DIPlus - xAdxDiHi_DIMinus)

xAdxDiHi_CR								= xAdxDiHi_ADX <= 22 ? color.new(colorxAdxDiHi_Buy, 80) : xAdxDiHi_ADX <= 34 ? color.new(colorxAdxDiHi_Buy, 60) : xAdxDiHi_ADX <= 46 ? color.new(colorxAdxDiHi_Buy, 40) : xAdxDiHi_ADX <= 58 ? color.new(colorxAdxDiHi_Buy, 25) : xAdxDiHi_ADX <= 70 ? color.new(colorxAdxDiHi_Buy, 10) : color.new(colorxAdxDiHi_Buy, 0)
xAdxDiHi_CG								= xAdxDiHi_ADX <= 22 ? color.new(colorxAdxDiHi_Short, 80) : xAdxDiHi_ADX <= 34 ? color.new(colorxAdxDiHi_Short, 60) : xAdxDiHi_ADX <= 46 ? color.new(colorxAdxDiHi_Short, 40) : xAdxDiHi_ADX <= 58 ? color.new(colorxAdxDiHi_Short, 25) : xAdxDiHi_ADX <= 70 ? color.new(colorxAdxDiHi_Short, 10) : color.new(colorxAdxDiHi_Short, 0)

//// ───────────────────────
/// ─── Visual ───
//// ───────────────────────

plot(strGlobalMultiHistogram == "Adx" ? xAdxDiHi_Didi : na,		style = plot.style_columns,		linewidth = 4,		color = xAdxDiHi_Didi >= 25 ? xAdxDiHi_CR : xAdxDiHi_CG,		transp = 50,		histbase = adxDiHi_Th ,		title = "DI")
plot(strGlobalMultiHistogram == "Adx" ? xAdxDiHi_Didi : na,		style = plot.style_line,		linewidth = 2,		color = xAdxDiHi_Didi >= 25 ? xAdxDiHi_CR : xAdxDiHi_CG,		transp = 50,		histbase = adxDiHi_Th ,		title = "Linea DI")

//// ─────────────────────────────────────────────────────────────────────
//// ─────────────────────────────────────────────────────────────────────
//// ─────────────────────────────────────────────────────────────────────

/// ╔═══════════════════════════════════╗
/// ║  Tsi & Divergences				║
/// ║  @	Allen.						║
/// ╚═══════════════════════════════════╝

//// ─────────────────────────────────────────────────────────────────────

//// ───────────────────────
/// ─── Vars ───
//// ───────────────────────

/// ─── Colors ───
colorTsiMuDiBaseLong					= color_gbl_long
colorTsiMuDiBaseShort					= color_gbl_short

colorTsiMuDiTendency					= color_gbl_neutral
colorTsiMuDiMultitimeframe				= color_gbl_neutral
colorTsiMuDiDivergBg					= color_gbl_black

colorTsiMuDiDivergLong					= color_gbl_buy
colorTsiMuDiDivergShort					= color_gbl_sell
colorTsiMuDiDivergNone					= color.new(color_gbl_black,		100)
colorTsiMuDiText						= color.new(color_gbl_text,			0)

/// ─── Inputs ───
groupTsiMuDiTSIVars						= 'TSI & Divergences'
vTsiMuDiLong							= input.int		(defval = 6,		title = 'Longitud de Compra',			group = globalTSIGroupTimeframe)
vTsiMuDiShort							= input.int		(defval = 13,		title = 'Longitud de Venta',			group = globalTSIGroupTimeframe)
vTsiMuDiSignal							= input.int		(defval = 5,		title = 'Longitud de Señal',			group = globalTSIGroupTimeframe)

/// ─── divergences ───
vTsiMuDiLBR								= 5									//	Corrección a la derecha
vTsiMuDiLBL								= 5									//	Corrección a la izquierda
vTsiMuDiRangeUpper						= 30								//	Rango de corrección maximo
vTsiMuDiRangeLower						= 2									//	Rango de corrección minimo
/// ─── Show ───
showTsiMuDiPlotDiverg					= input.bool	(defval = true,		title = 'Divergencias',					group = globalTSIGroupTimeframe,		inline = "diverg show")
showTsiMuDiPlotDivergScalp				= input.bool	(defval = true,		title = 'Scalp',						group = globalTSIGroupTimeframe,		inline = "diverg show")
showTsiMuDiCloudOn						= input.bool	(defval = true,		title = 'TSI Cloud',					group = globalTSIGroupTimeframe)

vTsiMuDiSource							= globalOHL.C[0]

//// ───────────────────────
/// ─── Functions ───
//// ───────────────────────

/// function tendency (smooth & tsi calculate)
FunTsiMuDiCalculateTendencyTSI(_source, _long, _short) =>
	_change								= ta.change(_source)
	_smooth_single						= ta.ema(_change, _long)
	_smooth_double						= ta.ema(_smooth_single, _short)
	_x									= 50
	_plus								= 50
	_smooth								= _smooth_double
	_smooth_abs							= math.abs(_smooth_double)
	_x * (_smooth / _smooth_abs) + _plus

//// ───────────────────────

/// function calculate TSI
FunTsiMuDiCalculateDoubleSmooth(_source, _long, _short) =>
	fist_smooth							= ta.ema(_source, _long)
	ta.ema(fist_smooth, _short)

FunTsiMuDiCalculateTSI(_source, _long, _short) =>
	_change								= ta.change(_source)
	_x									= 125
	_plus								= 50
	_smooth								= FunTsiMuDiCalculateDoubleSmooth(_change, _long, _short)
	_smooth_abs							= FunTsiMuDiCalculateDoubleSmooth(math.abs(_change), _long, _short)
	_x * (_smooth / _smooth_abs) + _plus

//// ───────────────────────
/// ─── Instances ───
//// ───────────────────────

/// Multitimeframe
/// instance function calculate multitimeframe Tsi
iTsiMuDiCalculateMultiTfTSI				= FunTsiMuDiCalculateTSI(vTsiMuDiSource, vTsiMuDiLong, vTsiMuDiShort)
iTsiMuDiCalculateMultiTfEMA				= ta.ema(iTsiMuDiCalculateMultiTfTSI, vTsiMuDiSignal)

/// instance function global timeframe
iTsiMuDiCalculateMultiTfTSIRange		= FunGlobalCalculateTimeframeRange(insGlobalTFCoefficient, FunGlobalTimeFrame(strGlobalMultiTimeFrame))

/// ─── Timeframe multitimeframe Tsi
arrTsiMuDiMultiTimeframeTicker			= request.security(syminfo.tickerid,	iTsiMuDiCalculateMultiTfTSIRange,	iTsiMuDiCalculateMultiTfTSI,	barmerge.gaps_on)

/// ─── plot color
insTsiMuDiMultiTimefPlotColor			= iTsiMuDiCalculateMultiTfTSI	> iTsiMuDiCalculateMultiTfEMA	? colorTsiMuDiBaseLong	: iTsiMuDiCalculateMultiTfTSI	<= iTsiMuDiCalculateMultiTfEMA	? colorTsiMuDiBaseShort	: na

/// Tendency
/// instances function calculate tendency  Tsi
iTsiMuDiCalculateTendencyTSI			= FunTsiMuDiCalculateTendencyTSI(vTsiMuDiSource, vTsiMuDiLong, vTsiMuDiShort)
iTsiMuDiCalculateTendencyEma			= ta.ema(iTsiMuDiCalculateTendencyTSI, vTsiMuDiSignal)

/// fill color tendency
insTsiMuDiCloudTendencyColor			= iTsiMuDiCalculateTendencyTSI	> iTsiMuDiCalculateTendencyEma	? colorTsiMuDiBaseLong	: iTsiMuDiCalculateTendencyTSI	<= iTsiMuDiCalculateTendencyEma	? colorTsiMuDiBaseShort		: na

/// PRESENT
/// instance function calculate present Tsi
iTsiMuDiCalculateTSI					= FunTsiMuDiCalculateTSI(vTsiMuDiSource, vTsiMuDiLong, vTsiMuDiShort)
iTsiMuDiCalculateEma					= ta.ema(iTsiMuDiCalculateTSI, vTsiMuDiSignal)

/// ─── plot color
insTsiMuDiPlotColor						= iTsiMuDiCalculateTSI			> iTsiMuDiCalculateEma			? colorTsiMuDiBaseLong	: iTsiMuDiCalculateTSI			<= iTsiMuDiCalculateEma			? colorTsiMuDiBaseShort	: na
/// ─── fill cloud color
insTsiMuDiCloudColor					= iTsiMuDiCalculateTSI			> iTsiMuDiCalculateEma			? colorTsiMuDiBaseLong	: iTsiMuDiCalculateTSI			<= iTsiMuDiCalculateEma			? colorTsiMuDiBaseShort	: na

//// ───────────────────────
/// ─── Display ───
//// ───────────────────────

/// ─── Plot

 /// plot multi timeframe
insTsiMuDiMultitimefTsiPlotLine			= plot(showTsiMuDiTSIMultitimeframe	? arrTsiMuDiMultiTimeframeTicker : na,							color = color.new(colorTsiMuDiMultitimeframe, 40),		linewidth = 2)
insTsiMuDiMultitimefEmaPlotLine			= plot(showTsiMuDiTSIMultitimeframe	? ta.ema(arrTsiMuDiMultiTimeframeTicker, vTsiMuDiSignal) : na,	color = color.new(colorTsiMuDiMultitimeframe, 50),		linewidth = 1)

/// plot tendency TSI
insTsiMuDiTendencyTsiPlotLine			= plot(showTsiMuDiTSITendency ? iTsiMuDiCalculateTendencyTSI : na,									color = color.new(colorTsiMuDiTendency, 77),			linewidth = 2)
insTsiMuDiTendencyEmaPlotLine			= plot(showTsiMuDiTSITendency ? ta.ema(iTsiMuDiCalculateTendencyTSI,	vTsiMuDiSignal) : na,		color = color.new(colorTsiMuDiTendency, 77),			linewidth = 2)

/// fill tendency
fill(insTsiMuDiTendencyTsiPlotLine, insTsiMuDiTendencyEmaPlotLine,																		color = color.new(insTsiMuDiCloudTendencyColor, 85))

/// plot present TSI
plot(showTsiMuDiTSIDivergs				? iTsiMuDiCalculateTSI	: na,																		color = color.new(colorTsiMuDiDivergBg, 60),					linewidth = 6)		//	plot TSI blue
plot(showTsiMuDiTSIDivergs				? ta.ema(iTsiMuDiCalculateTSI,	vTsiMuDiSignal)	: na,												color = color.new(colorTsiMuDiDivergBg, 60),					linewidth = 6)		//	plot EMA blue
insTsiMuDiTsiPlotLine					= plot(showTsiMuDiTSIDivergs ? iTsiMuDiCalculateTSI	: na,											color = color.new(insTsiMuDiPlotColor, 30),				linewidth = 2)		//	plot TsiSI
insTsiMuDiEmaPlotLine					= plot(showTsiMuDiTSIDivergs ? ta.ema(iTsiMuDiCalculateTSI,	vTsiMuDiSignal)	: na,					color = color.new(insTsiMuDiPlotColor, 30),				linewidth = 2)		//	plot EMA

/// fill present
fill(insTsiMuDiTsiPlotLine, insTsiMuDiEmaPlotLine,																						color = showTsiMuDiCloudOn ? color.new(insTsiMuDiCloudColor, 70) : na)						//	fill

//// ───────────────────────
/// ─── Divergences ───
//// ───────────────────────

insTsiMuDiPLFound						= na(ta.pivotlow(iTsiMuDiCalculateTSI, vTsiMuDiLBL, vTsiMuDiLBR)) ? false : true
insTsiMuDiPHFound						= na(ta.pivothigh(iTsiMuDiCalculateTSI, vTsiMuDiLBL, vTsiMuDiLBR)) ? false : true

FunTsiMuDi_inRange(cond) =>
	insTsiMuDiBars						= ta.barssince(cond == true)
	vTsiMuDiRangeLower					<= insTsiMuDiBars and insTsiMuDiBars <= vTsiMuDiRangeUpper

//// ───────────────────────
/// ─── Compra regular ───
//// ───────────────────────

/// ─── Osc: Higher Low ─ Price: Lower Low
tsiDiInsOSCHL							= iTsiMuDiCalculateTSI[vTsiMuDiLBR]	> ta.valuewhen(insTsiMuDiPLFound, iTsiMuDiCalculateTSI[vTsiMuDiLBR], 1)	and FunTsiMuDi_inRange(insTsiMuDiPLFound[1])
tsiDiInsPRICELL							= low[vTsiMuDiLBR]					< ta.valuewhen(insTsiMuDiPLFound, low[vTsiMuDiLBR], 1)
tsiDiInsBULLCond						= showTsiMuDiPlotDiverg				and tsiDiInsPRICELL	and tsiDiInsOSCHL	and insTsiMuDiPLFound

plot(showTsiMuDiTSIDivergs				and insTsiMuDiPLFound				? iTsiMuDiCalculateTSI[vTsiMuDiLBR] : na,
			  offset					= -vTsiMuDiLBR,
			  title						= 'Confirmacion de Compra',
			  linewidth					= 2,
			  color						= tsiDiInsBULLCond ? color.new(colorTsiMuDiDivergLong, 10) : colorTsiMuDiDivergNone)

plotshape(showTsiMuDiTSIDivergs			and	tsiDiInsBULLCond				? iTsiMuDiCalculateTSI[vTsiMuDiLBR] : na,
			  offset					= -vTsiMuDiLBR,
			  title						= 'Etiqueta de Compra',
			  text						= ' Compra ',
			  style						= shape.labelup,
			  location					= location.absolute,
			  color						= color.new(colorTsiMuDiDivergLong, 10),
			  textcolor					= colorTsiMuDiText)

//// ───────────────────────
/// ─── Compra scalp ───
//// ───────────────────────

/// ─── Osc: Lower Low ─ Price: Higher Low
tsiDiInsOSCLL							= iTsiMuDiCalculateTSI[vTsiMuDiLBR]	< ta.valuewhen(insTsiMuDiPLFound, iTsiMuDiCalculateTSI[vTsiMuDiLBR], 1)	and FunTsiMuDi_inRange(insTsiMuDiPLFound[1])
tsiDiInsPRICEHL							= low[vTsiMuDiLBR]					> ta.valuewhen(insTsiMuDiPLFound, low[vTsiMuDiLBR], 1)
tsiDiInsHiddenBullCond					= showTsiMuDiPlotDivergScalp		and tsiDiInsPRICEHL	and tsiDiInsOSCLL	and insTsiMuDiPLFound

plot(showTsiMuDiTSIDivergs				and insTsiMuDiPLFound				? iTsiMuDiCalculateTSI[vTsiMuDiLBR] : na,
			  offset					= -vTsiMuDiLBR,
			  title						= 'Confirmación de Compra scalp',
			  linewidth					= 2,
			  color						= tsiDiInsHiddenBullCond ? color.new(colorTsiMuDiDivergLong, 40) : colorTsiMuDiDivergNone)

plotshape(showTsiMuDiTSIDivergs			and tsiDiInsHiddenBullCond			? iTsiMuDiCalculateTSI[vTsiMuDiLBR] : na,
			  offset					= -vTsiMuDiLBR,
			  title						= 'Etiqueta de Compra scalp',
			  text						= ' △ scalp ',
			  style						= shape.labelup,
			  location					= location.absolute,
			  color						= color.new(colorTsiMuDiDivergLong, 40),
			  textcolor					= colorTsiMuDiText)

//// ───────────────────────
/// ─── Venta regular ───
//// ───────────────────────

/// ─── Osc: Lower High ─ Price: Higher High
tsiDiInsOSCLH							= iTsiMuDiCalculateTSI[vTsiMuDiLBR]	< ta.valuewhen(insTsiMuDiPHFound, iTsiMuDiCalculateTSI[vTsiMuDiLBR], 1) and FunTsiMuDi_inRange(insTsiMuDiPHFound[1])
tsiDiInsPRICEHH							= high[vTsiMuDiLBR]					> ta.valuewhen(insTsiMuDiPHFound, high[vTsiMuDiLBR], 1)
tsiDiInsBEARCond						= showTsiMuDiPlotDiverg				and tsiDiInsPRICEHH	and tsiDiInsOSCLH	and insTsiMuDiPHFound

plot(showTsiMuDiTSIDivergs				and insTsiMuDiPHFound				? iTsiMuDiCalculateTSI[vTsiMuDiLBR] : na,
			  offset					= -vTsiMuDiLBR,
			  title						= 'Confirmación de Venta',
			  linewidth					= 2,
			  color						= tsiDiInsBEARCond ? color.new(colorTsiMuDiDivergShort, 10) : colorTsiMuDiDivergNone)

plotshape(showTsiMuDiTSIDivergs			and tsiDiInsBEARCond				? iTsiMuDiCalculateTSI[vTsiMuDiLBR] : na,
			  offset					= -vTsiMuDiLBR,
			  title						= 'Etiqueta de Venta',
			  text						= ' Venta ',
			  style						= shape.labeldown,
			  location					= location.absolute,
			  color						= color.new(colorTsiMuDiDivergShort, 10),
			  textcolor					= colorTsiMuDiText)

//// ───────────────────────
/// ─── Venta scalp ───
//// ───────────────────────

/// ─── Osc: Higher High ─ Price: Lower High
tsiDiInsOSCHH							= iTsiMuDiCalculateTSI[vTsiMuDiLBR]	> ta.valuewhen(insTsiMuDiPHFound, iTsiMuDiCalculateTSI[vTsiMuDiLBR], 1) and FunTsiMuDi_inRange(insTsiMuDiPHFound[1])
tsiDiInsPRICELH							= high[vTsiMuDiLBR]					< ta.valuewhen(insTsiMuDiPHFound, high[vTsiMuDiLBR], 1)
tsiDiInsHiddenBearCond					= showTsiMuDiPlotDivergScalp		and tsiDiInsPRICELH	and tsiDiInsOSCHH	and insTsiMuDiPHFound

plot(showTsiMuDiTSIDivergs				and insTsiMuDiPHFound				? iTsiMuDiCalculateTSI[vTsiMuDiLBR] : na,
			  offset					= -vTsiMuDiLBR,
			  title						= 'Confirmación de Venta scalp',
			  linewidth					= 2,
			  color						= tsiDiInsHiddenBearCond ? color.new(colorTsiMuDiDivergShort, 40) : colorTsiMuDiDivergNone)

plotshape(showTsiMuDiTSIDivergs			and tsiDiInsHiddenBearCond			? iTsiMuDiCalculateTSI[vTsiMuDiLBR] : na,
			  offset					= -vTsiMuDiLBR,
			  title						= 'Etiqueta de Venta scalp',
			  text						= ' ▽ scalp ',
			  style						= shape.labeldown,
			  location					= location.absolute,
			  color						= color.new(colorTsiMuDiDivergShort, 40),
			  textcolor					= colorTsiMuDiText)

//// ─────────────────────────────────────────────────────────────────────
//// ─────────────────────────────────────────────────────────────────────
//// ─────────────────────────────────────────────────────────────────────

/// ╔═══════════════════════════════════════╗
/// ║	TSI Panel Multi Timeframe			║
/// ║	@	Allen.							║
/// ╚═══════════════════════════════════════╝

//// ─────────────────────────────────────────────────────────────────────

//// ───────────────────────
/// ─── TSI Obs MTF ───
/// ─── TSI Box ───
//// ───────────────────────

colorTsiObsPnl_Buy						= color_gbl_long
colorTsiObsPnl_Sell						= color_gbl_short
colorTsiObsPnl_Neutral					= color_gbl_neutral
colorTsiObsPnl_White					= color_gbl_white
colorTsiObsPnl_Black					= color_gbl_black
colorTsiObsPnl_Text						= color_gbl_text
colorTsiObsPnl_TiPnBg					= color_gbl_extra

/// ─── Inputs
tsiObsPnlGroupTimeframes				=				"Timeframe Panel"
showTsiObsPnlTimeframesPanel			= input.bool	(true,				title = "Panel TSI",			group = tsiObsPnlGroupTimeframes)
showTsiObsPnlTF05m						= input.bool	(false,				title = "5m   ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr")
showTsiObsPnlTF15m						= input.bool	(true,				title = "15m  ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr")
showTsiObsPnlTF30m						= input.bool	(false,				title = "30m  ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr")
showTsiObsPnlTF1h						= input.bool	(true,				title = "1 H  ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr2")
showTsiObsPnlTF2h						= input.bool	(true,				title = "2 H  ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr2")
showTsiObsPnlTF3h						= input.bool	(true,				title = "3 H  ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr2")
showTsiObsPnlTF4h						= input.bool	(false,				title = "4 H  ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr3")
showTsiObsPnlTF1d						= input.bool	(true,				title = "1 D  ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr3")
showTsiObsPnlTF1w						= input.bool	(false,				title = "1 S  ",				group = tsiObsPnlGroupTimeframes,		inline = "timefr3")

tsiObsPnlGroupSignal					=				"Signal Panel"
showTsiObsPnlSignalPanel				= input.bool	(true,				title = "Panel TSI Signal",		group = tsiObsPnlGroupSignal)
showTsiObsPnlSignalTsi					= input.bool	(true,				title = "Tsi ",					group = tsiObsPnlGroupSignal,			inline = "signal")
showTsiObsPnlSignalMtf					= input.bool	(true,				title = "Mtf ",					group = tsiObsPnlGroupSignal,			inline = "signal")
showTsiObsPnlSignalRsi					= input.bool	(false,				title = "Rsi ",					group = tsiObsPnlGroupSignal,			inline = "signal")
showTsiObsPnlSignalMfi					= input.bool	(true,				title = "Mfi ",					group = tsiObsPnlGroupSignal,			inline = "signal")
showTsiObsPnlSignalAdx					= input.bool	(true,				title = "Adx ",					group = tsiObsPnlGroupSignal,			inline = "signal")

tsiObsPnl_PosiVert						= input.string	(defval = "abajo",	title = " Y: ",					group = tsiObsPnlGroupTimeframes,		inline = "ubic",
		  options						=				["arriba", "medio","abajo"])
tsiObsPnl_PosiHoriz						= input.string	(defval = "centro",	title = " X: ",					group = tsiObsPnlGroupTimeframes,		inline = "ubic",
		  options						=				["izquierda", "centro","derecha"])

tsiObsPnl_LocatSignalVert				= input.string	(defval = "medio",	title = " Y: ",					group = tsiObsPnlGroupSignal,			inline = "ubic signal",
		  options						=				["arriba", "medio","abajo"])
tsiObsPnl_LocatSignalHoriz				= input.string	(defval = "derecha",title = " X: ",					group = tsiObsPnlGroupSignal,			inline = "ubic signal",
		  options						=				["izquierda", "derecha"])

stTsiObsPnl_TextSize					= input.string	(defval = "normal",	title = "Tamaño de texto",
		  options						= ["auto","tiny","small","normal","large","huge"])

vTsiObsPnl_RsiLength					= 14

/// ───────────────────────
/// ─── Types
/// ───────────────────────

/// ───────────────────────
/// ─── Functions
/// ───────────────────────
/// ─── RSI
tsiObsPnlRSI							= ta.rsi(globalOHL.C, vTsiObsPnl_RsiLength)

/// ─── TSI invoke
tsiObsPnlTSI							= iTsiMuDiCalculateMultiTfTSI
tsiObsPnlMTFRange						= FunGlobalCalculateTimeframeRange(insGlobalTFCoefficient, timeframe.period)
tsiObsPnlEma							= iTsiMuDiCalculateMultiTfEMA
tsiObsPnlMFI							= adapMonIfVAL
tsiObsPnlADX							= xAdxDiHi_Didi

/// instance function global timeframe
iTsiObsPnlCalcSignal					= timeframe.period

/// ─── TSI timeframes
vTsiObsPnlTF05m							= request.security(syminfo.tickerid,		"5",		tsiObsPnlTSI)
vTsiObsPnlTF15m							= request.security(syminfo.tickerid,		"15",		tsiObsPnlTSI)
vTsiObsPnlTF30m							= request.security(syminfo.tickerid,		"30",		tsiObsPnlTSI)
vTsiObsPnlTF1h							= request.security(syminfo.tickerid,		"60",		tsiObsPnlTSI)
vTsiObsPnlTF2h							= request.security(syminfo.tickerid,		"120",		tsiObsPnlTSI)
vTsiObsPnlTF3h							= request.security(syminfo.tickerid,		"180",		tsiObsPnlTSI)
vTsiObsPnlTF4h							= request.security(syminfo.tickerid,		"240",		tsiObsPnlTSI)
vTsiObsPnlTF1d							= request.security(syminfo.tickerid,		"D",		tsiObsPnlTSI)
vTsiObsPnlTF1w							= request.security(syminfo.tickerid,		"W",		tsiObsPnlTSI)

/// ─── TSI timeframes signal
[vTsiObsPnlTFSignalTsi,	vTsiObsPnlTFSignalTsi_2,	vTsiObsPnlTFSignalTsi_3,	vTsiObsPnlTFSignalTsi_4]	= request.security(syminfo.tickerid,	iTsiObsPnlCalcSignal,	[tsiObsPnlTSI,	tsiObsPnlTSI[1],	tsiObsPnlTSI[2],	tsiObsPnlTSI[3]],	lookahead = barmerge.lookahead_on)
[vTsiObsPnlTFSignalEma,	vTsiObsPnlTFSignalEma_2,	vTsiObsPnlTFSignalEma_3,	vTsiObsPnlTFSignalEma_4]	= request.security(syminfo.tickerid,	iTsiObsPnlCalcSignal,	[tsiObsPnlEma,	tsiObsPnlEma[1],	tsiObsPnlEma[2],	tsiObsPnlEma[3]],	lookahead = barmerge.lookahead_on)
[vTsiObsPnlTFSignalMtf,	vTsiObsPnlTFSignalMtf_2,	vTsiObsPnlTFSignalMtf_3,	vTsiObsPnlTFSignalMtf_4]	= request.security(syminfo.tickerid,	tsiObsPnlMTFRange,		[tsiObsPnlTSI,	tsiObsPnlTSI[1],	tsiObsPnlTSI[2],	tsiObsPnlTSI[3]],	lookahead = barmerge.lookahead_on)
[vTsiObsPnlTFSignalRsi,	vTsiObsPnlTFSignalRsi_2,	vTsiObsPnlTFSignalRsi_3,	vTsiObsPnlTFSignalRsi_4]	= request.security(syminfo.tickerid,	iTsiObsPnlCalcSignal,	[tsiObsPnlRSI,	tsiObsPnlRSI[1],	tsiObsPnlRSI[2],	tsiObsPnlRSI[3]],	lookahead = barmerge.lookahead_on)
[vTsiObsPnlTFSignalMfi,	vTsiObsPnlTFSignalMfi_2,	vTsiObsPnlTFSignalMfi_3,	vTsiObsPnlTFSignalMfi_4]	= request.security(syminfo.tickerid,	iTsiObsPnlCalcSignal,	[tsiObsPnlMFI,	tsiObsPnlMFI[1],	tsiObsPnlMFI[2],	tsiObsPnlMFI[3]],	lookahead = barmerge.lookahead_on)
[vTsiObsPnlTFSignalAdx,	vTsiObsPnlTFSignalAdx_2,	vTsiObsPnlTFSignalAdx_3,	vTsiObsPnlTFSignalAdx_4]	= request.security(syminfo.tickerid,	iTsiObsPnlCalcSignal,	[tsiObsPnlADX,	tsiObsPnlADX[1],	tsiObsPnlADX[2],	tsiObsPnlADX[3]],	lookahead = barmerge.lookahead_on)

/// ─── New table
var vTsiPnlNewTable						= table.new(
	  position							= FunGlobalVertical(tsiObsPnl_PosiVert) + "_" + FunGlobalHorizontal(tsiObsPnl_PosiHoriz),
	  columns							= 11,
	  rows								= 1,
	  border_width						= 2,
	  frame_color						= color.new(colorTsiObsPnl_Black, 15),
	  force_overlay						= true)

/// ─── New table signal
var vTsiPnlNewTableSignal				= table.new(
		  position						= FunGlobalVertical(tsiObsPnl_LocatSignalVert) + "_" + FunGlobalHorizontal(tsiObsPnl_LocatSignalHoriz),
		  columns						= 1,
		  rows							= 5,
		  border_width					= 2,
		  frame_color					= color.new(colorTsiObsPnl_Black, 15))

/// ─── Function table cells
FunTsiObsPnlCalculateCell(_col, _row, _timeframe, _value) =>
	_cell_color							= _value >= 100 ? colorTsiObsPnl_Buy : _value <= 0 ? colorTsiObsPnl_Sell : colorTsiObsPnl_Neutral
	_opacity							= _value >= 100 or _value <= 0 ? 20 : _value >= 85 or _value <= 15 ? 40 : 65
	_cell_text							= _timeframe + "\n" + str.tostring(_value, "#.00")
	_txtsize							= stTsiObsPnl_TextSize

	table.cell							(vTsiPnlNewTable, _col, _row, _cell_text,
		  bgcolor						= color.new(_cell_color, _opacity),
		  text_size						= _txtsize,
		  text_color					= colorTsiObsPnl_Text,
		  width							= 5)

/// ─── Function table name
FunTsiObsPnlCalculateCellNow(_col, _row) =>
	_cell_text							= "TSI"

	table.cell							(vTsiPnlNewTable, _col, _row, _cell_text,
		  bgcolor						= color.new(colorTsiObsPnl_TiPnBg, 10),
  		  text_size						= stTsiObsPnl_TextSize,
		  text_color					= color.new(colorTsiObsPnl_Text, 10),
		  width							= 3)

/// ─── Function table signal
FunTsiObsPnlCalculateCellSignal(_col, _row, _title, _var, _var2, _var3, _var4, _min, _max) =>
	/// ─── signal buy/sell
	_if_buy								= _var		> _var3		and _var2		> _var4		and	_var > vTsiObsPnlTFSignalEma	and	_var < _min
	_if_sell							= _var		< _var3		and _var2		< _var4		and _var < vTsiObsPnlTFSignalEma	and	_var > _max
	_if_condition						= _if_sell	?	" 🔴 ⬊ "	:	_if_buy	?	" 🟢 ⬈ "	:	"  "

	_div								= 6
	_fract_max							= math.round(_max - (_max / _div))
	_fract_min							= math.ceil(_min + (_max / _div))

	_cell_color							= _var >= _max ? colorTsiObsPnl_Sell : _var <= _min ? colorTsiObsPnl_Buy : colorTsiObsPnl_Neutral
	_signal_opacity						= _var >= _max or _var <= _min ? 30 : _var >= _fract_max or _var <= _fract_min ? 40 : 65
	_cell_text							= _title + "\n" + str.tostring(_var, "#.00") + "\n" +_if_condition

	/// ─── table
	table.cell							(vTsiPnlNewTableSignal, _col, _row, _cell_text,
		  bgcolor						= color.new(_cell_color, _signal_opacity),
		  text_size						= stTsiObsPnl_TextSize,
		  text_color					= colorTsiObsPnl_Text,
		  width							= 4,
		  height						= 23)

/// ───────────────────────
/// ─── Visual
/// ───────────────────────

/// ─── Table TSI
if showTsiObsPnlTimeframesPanel
	FunTsiObsPnlCalculateCellNow		(0,	0)

	FunTsiObsPnlCalculateCell			(1,	0,		"Actual",	tsiObsPnlTSI)

	if showTsiObsPnlTF05m
		FunTsiObsPnlCalculateCell		(2,	0,		"5 m",		vTsiObsPnlTF05m)
	if showTsiObsPnlTF15m
		FunTsiObsPnlCalculateCell		(3,	0,		"15 m",		vTsiObsPnlTF15m)
	if showTsiObsPnlTF30m
		FunTsiObsPnlCalculateCell		(4,	0,		"30 m",		vTsiObsPnlTF30m)
	if showTsiObsPnlTF1h
		FunTsiObsPnlCalculateCell		(5,	0,		"1 H",		vTsiObsPnlTF1h)
	if showTsiObsPnlTF2h
		FunTsiObsPnlCalculateCell		(6,	0,		"2 H",		vTsiObsPnlTF2h)
	if showTsiObsPnlTF3h
		FunTsiObsPnlCalculateCell		(7,	0,		"3 H",		vTsiObsPnlTF3h)
	if showTsiObsPnlTF4h
		FunTsiObsPnlCalculateCell		(8,	0,		"4 H",		vTsiObsPnlTF4h)
	if showTsiObsPnlTF1d
		FunTsiObsPnlCalculateCell		(9,	0,		"1 D",		vTsiObsPnlTF1d)
	if showTsiObsPnlTF1w
		FunTsiObsPnlCalculateCell		(10, 0,		"1 S",		vTsiObsPnlTF1w)

/// ─── Table Signal
if showTsiObsPnlSignalPanel
	if showTsiObsPnlSignalTsi
		FunTsiObsPnlCalculateCellSignal		(0,	0,	"Tsi",	vTsiObsPnlTFSignalTsi,	vTsiObsPnlTFSignalTsi_2,	vTsiObsPnlTFSignalTsi_3,	vTsiObsPnlTFSignalTsi_4,	0,		100)
	if showTsiObsPnlSignalMtf
		FunTsiObsPnlCalculateCellSignal		(0,	1,	"Mtf",	vTsiObsPnlTFSignalMtf,	vTsiObsPnlTFSignalMtf_2,	vTsiObsPnlTFSignalMtf_3,	vTsiObsPnlTFSignalMtf_4,	20,		80)
	if showTsiObsPnlSignalRsi
		FunTsiObsPnlCalculateCellSignal		(0,	3,	"Rsi",	vTsiObsPnlTFSignalRsi,	vTsiObsPnlTFSignalRsi_2,	vTsiObsPnlTFSignalRsi_3,	vTsiObsPnlTFSignalRsi_4,	25,		75)
	if showTsiObsPnlSignalMfi
		FunTsiObsPnlCalculateCellSignal		(0, 4,	"Mfi",	vTsiObsPnlTFSignalMfi,	vTsiObsPnlTFSignalMfi_2,	vTsiObsPnlTFSignalMfi_3,	vTsiObsPnlTFSignalMfi_4,	-10,	110)
	if showTsiObsPnlSignalAdx
		FunTsiObsPnlCalculateCellSignal		(0,	2,	"Adx",	vTsiObsPnlTFSignalAdx,	vTsiObsPnlTFSignalAdx_2,	vTsiObsPnlTFSignalAdx_3,	vTsiObsPnlTFSignalAdx_4,	10,		40)

//// ─────────────────────────────────────────────────────────────────────
